#!/bin/bash
set -euo pipefail

# ─────────────────────────────────────────────
# Open GitHub PRs for all vibe branches
# ─────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Opening PRs for all vibe branches"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

STACKS=("react-tailwind" "svelte-css" "vue-tailwind" "vanilla-html-css-js" "comparison-report")
LABELS=("React + Tailwind" "Svelte + CSS" "Vue + Tailwind" "Vanilla HTML/CSS/JS" "Comparison Report")
EMOJIS=("⚛️" "🔥" "💚" "📄" "📊")

SUCCESS=0
FAILED=0

for i in "${!STACKS[@]}"; do
  STACK="${STACKS[$i]}"
  LABEL="${LABELS[$i]}"
  EMOJI="${EMOJIS[$i]}"

  echo "  Creating PR for vibe/${STACK}..."

  if gh pr create \
    --head "vibe/${STACK}" \
    --title "${EMOJI} Vibe: ${LABEL}" \
    --body "$(cat <<EOF
## Vibe Translator — ${LABEL}

Auto-generated by Oz Cloud Agents.

### Stack
**${LABEL}**

### How to Review
\`\`\`bash
git fetch origin
git checkout vibe/${STACK}
\`\`\`

### Run Locally
\`\`\`bash
git checkout vibe/${STACK}
cd ${STACK%%-*}  # navigate to the stack directory
npm install && npm run dev  # (skip for vanilla — just open index.html)
\`\`\`

---
*Generated by [Vibe Translator](https://github.com) powered by [Oz](https://www.warp.dev/oz)*
EOF
)" 2>/dev/null; then
    echo "  [done] PR created for vibe/${STACK}"
    SUCCESS=$((SUCCESS + 1))
  else
    echo "  [skip] PR already exists or failed for vibe/${STACK}"
    FAILED=$((FAILED + 1))
  fi

  echo ""
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Done! Created: ${SUCCESS}  Skipped: ${FAILED}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  View all PRs:"
echo "    gh pr list"
echo ""
